### ISSUE TITLE
Arduino Uno Wiring for 3-Wire SPI

### ISSUE THREAD

**Issue by frd-na** [Infineon/DPS368-Library-Arduino#3]
Tried the spi_interrupt.ino and the wiring below but can't make it work. Would appreciate any help from anyone who made it work.

Arduino Uno - DPS368
(13) SCL         - SCK
(2) Interrupt   - MOSI
(10) SS            - CS

**Comment by HoneyDhandhukia** [comment]
Please check the pin connections for Arduino Uno. You can refer to the link https://github.com/Infineon/DPS368-Library-Arduino/wiki for further clarification and please ensure you are using level shifters for interfacing Arduino Uno and DPS368.
